lumina:
  version: 1.0.0

components:
  promop:
    repository: https://github.com/healthkey-ai/promop.git
    clone_url: git@github.com:healthkey-ai/promop.git
    git_ref: d941cf65f3f6598f7e8631af8575aa1e014aa62c
  lumina-wearables:
    repository: https://github.com/HarvardGlobal/lumina-wearables.git
    clone_url: git@github.com:HarvardGlobal/lumina-wearables.git
    git_ref: f4421e5b5ab8608c8fe37a10d6395696b106c74b

schemas:
  archive: 1.0.0
  wearable_common_data_schema: 1.0.0
  wearable_metric_registry: 1.0.0

standards:
  omop_cdm: "5.4"
  ohdsi_vocabulary_release: "UNSET"
