lumina:
  version: 1.1.2

components:
  promop:
    repository: https://github.com/healthkey-ai/promop.git
    clone_url: git@github.com:healthkey-ai/promop.git
    git_ref: d941cf65f3f6598f7e8631af8575aa1e014aa62c
  lumina-wearables:
    repository: https://github.com/HarvardGlobal/lumina-wearables.git
    clone_url: git@github.com:HarvardGlobal/lumina-wearables.git
    git_ref: 129ee95c479f9fbcde67f809a684f64fbc098082
    version: 1.1.2
  open-wearables:
    repository: https://github.com/the-momentum/open-wearables.git
    clone_url: https://github.com/the-momentum/open-wearables.git
    git_ref: cb3ad1fd1141138179d27f7e787a1d0049a071c9
    version: 0.7.0

schemas:
  archive: 1.0.0
  wearable_common_data_schema: 1.1.0
  wearable_metric_registry: 0.1.1

standards:
  omop_cdm: "5.4"
  ohdsi_vocabulary_release: "UNSET"
